"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "/custom_components/battery_notes/translations/en.json",
    "translation": "/custom_components/battery_notes/translations/%locale%.json",
    "languages_mapping": {
            "locale": {
                "ca": "ca",
                "da": "da",
                "de": "de",
                "el": "el",
                "en": "en",
                "es-ES": "es-ES",
                "fi": "fi",
                "fr": "fr",
                "hu": "hu",
                "it": "it",
                "lt": "lt",
                "no": "no",
                "nl": "nl",
                "pl": "pl",
                "pt": "pt",
                "ru": "ru",
                "sk": "sk",
                "sv-SE": "sv-SE",
                "sr-CS": "sr-Latn",
                "ur-IN": "ur-IN"
            }
        }
  }
]
