site_name: Battery Notes for Home Assistant
site_url: https://andrew-codechimp.github.io/HA-Battery-Notes
repo_url: https://github.com/andrew-codechimp/HA-Battery-Notes
docs_dir: docs

nav:
  - Home: index.md
  - Entities: entities.md
  - Events: events.md
  - Actions: actions.md
  - Library: library.md
  - Configuration: configuration.md
  - Community: community.md
  - Blueprints: blueprints.md
  - Translations: translations.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
