blueprint:
  name: Battery Notes - Battery Replaced
  description: Set the battery replaced automatically when the battery increased
  author: andrew-codechimp
  source_url: https://raw.githubusercontent.com/andrew-codechimp/HA-Battery-Notes/main/docs/blueprints/battery_notes_battery_replaced.yaml
  domain: automation

  input:
    on_replaced_actions:
      name: On Replaced Actions
      description: User actions to run on battery replacement, the battery is marked as replaced automatically. Use any event data via trigger.event.data.xxx
      default: []
      selector:
        action:

trigger:
  - platform: event
    event_type: battery_notes_battery_increased

condition: []

action:
  - service: battery_notes.set_battery_replaced
    data:
      device_id: "{{ trigger.event.data.device_id }}"
  - alias: "Run user on replaced actions"
    choose: []
    default: !input 'on_replaced_actions'

mode: queued