blueprint:
  name: Battery Notes - Battery Threshold
  description: Actions to perform when the battery threshold is met
  author: andrew-codechimp
  source_url: https://raw.githubusercontent.com/andrew-codechimp/HA-Battery-Notes/main/docs/blueprints/battery_notes_battery_threshold.yaml
  domain: automation

  input:
    low_notification:
      name: Battery Low Notification
      description: Create a persistent notification when the battery is low.
      default: True
      selector:
        boolean:
    high_notification:
      name: Remove Low Notification
      description: Remove the persistent notification when the battery is no longer low. Use any event data via trigger.event.data.xxx
      default: True
      selector:
        boolean:
    excluded_devices:
      name: Devices to exclude (Optional)
      description: Devices that you do not want to trigger this automation.
      default:
      selector:
        device:
          multiple: true
          entity:
            - integration: battery_notes
    on_low_actions:
      name: On Low Actions
      description: User actions to run on battery low. Use any event data via trigger.event.data.xxx
      default: []
      selector:
        action:
    on_high_actions:
      name: On High Actions
      description: User actions to run on battery returning from low. Use any event data via trigger.event.data.xxx
      default: []
      selector:
        action:

variables:
  low_notification: !input low_notification
  high_notification: !input high_notification
  excluded_devices: !input excluded_devices

trigger:
  - platform: event
    event_type: battery_notes_battery_threshold
    event_data:
      battery_low: true
    id: low
    alias: Battery went low
  - platform: event
    event_type: battery_notes_battery_threshold
    event_data:
      battery_low: false
    id: high
    alias: Battery went high

condition:
  - condition: template
    value_template: |-
      {{ trigger.event.data.device_id not in excluded_devices}}

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - low
        sequence:
          - if:
              - condition: template
                value_template: "{{ low_notification }}"
            then:
              - service: persistent_notification.create
                data:
                  title: |
                    {{ trigger.event.data.device_name }} Battery Low
                  notification_id: "battery_notes_threshold {{ trigger.event.data.device_id }}-{{ trigger.event.data.source_entity_id }}"
                  message: >
                    The device has a battery level of {{
                    trigger.event.data.battery_level }}% {{ '\n' -}} You need {{
                    trigger.event.data.battery_quantity }}× {{
                    trigger.event.data.battery_type }}
          - alias: "Run user on low actions"
            choose: []
            default: !input 'on_low_actions'
      - conditions:
          - condition: trigger
            id:
              - high
        sequence:
          - if:
              - condition: template
                value_template: "{{ low_notification }}"
            then:
              - service: persistent_notification.dismiss
                data:
                  notification_id: "battery_notes_threshold {{ trigger.event.data.device_id }}-{{ trigger.event.data.source_entity_id }}"
          - alias: "Run user on high actions"
            choose: []
            default: !input 'on_high_actions'

mode: queued