blueprint:
  name: Battery Notes - Battery Replaced
  description: Set the battery replaced automatically when the battery goes above 98%
  author: andrew-codechimp
  source_url: https://raw.githubusercontent.com/andrew-codechimp/HA-Battery-Notes/main/docs/blueprints/battery_notes_battery_replaced.yaml
  domain: automation

  input:
    battery_entities:
      name: Battery Entities
      description: 'Specify which battery entities should trigger this automation.'
      selector:
        entity:
          device_class: battery
          multiple: true
mode: queued
trigger:
  - platform: state
    entity_id: !input 'battery_entities'
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition:
  - condition: template
    value_template: >-
      {{ trigger.from_state is not none and trigger.from_state.state not in
      ['unavailable','unknown'] and trigger.from_state.state|float(0) < 100 and
      trigger.to_state.state|float(0) > 98 }}
action:
  - service: battery_notes.set_battery_replaced
    data:
      device_id: "{{ device_id(trigger.entity_id) }}"
    enabled: true
