blueprint:
  name: Battery Notes - Battery Threshold
  description: Actions to perform when the battery threshold is met
  author: andrew-codechimp
  source_url: https://raw.githubusercontent.com/andrew-codechimp/HA-Battery-Notes/main/docs/blueprints/battery_notes_battery_threshold.yaml
  domain: automation

  input:
    low_notification:
      name: Battery Low Notification
      description: Create a persistent notification when the battery is low.
      default: True
      selector:
        boolean:
    high_notification:
      name: Remove Low Notification
      description: Remove the persistent notification when the battery is no longer low.
      default: True
      selector:
        boolean:
    exclude_devices_enabled:
      name: Enable Exclude Devices Filter
      description: Do not trigger for specific devices when enabled.
      default: true
      selector:
        boolean:        
    excluded_devices:
      name: Devices to exclude (Optional)
      description: Devices that you do not want to trigger this automation.
      default:
      selector:
        device:
          multiple: true
          entity:
            - integration: battery_notes
    include_devices_enabled:
      name: Enable Include Devices Filter
      description: Only trigger for specific devices when enabled.
      default: false
      selector:
        boolean:
    include_devices:
      name: Devices to include (Optional)
      description: When enabled above, only these devices will trigger this automation.
      default:
      selector:
        device:
          multiple: true
          entity:
            - integration: battery_notes
    additional_conditions:
      name: Additional conditions
      description: |
        Extra conditions you may want to add to this automation
        (Example: Home occupied)
      default: []
      selector:
        condition:
    on_low_actions:
      name: On Low Actions
      description: User actions to run on battery low. Use any event data via trigger.event.data.xxx
      default: []
      selector:
        action:
    on_high_actions:
      name: On High Actions
      description: User actions to run on battery returning from low. Use any event data via trigger.event.data.xxx
      default: []
      selector:
        action:

variables:
  low_notification: !input low_notification
  high_notification: !input high_notification
  exclude_devices_enabled: !input exclude_devices_enabled
  excluded_devices: !input excluded_devices
  include_devices_enabled: !input include_devices_enabled
  include_devices: !input include_devices

triggers:
  - trigger: event
    event_type: battery_notes_battery_threshold
    event_data:
      battery_low: true
    id: low
    alias: Battery went low
  - trigger: event
    event_type: battery_notes_battery_threshold
    event_data:
      battery_low: false
    id: high
    alias: Battery went high

conditions:
  - condition: template
    value_template: |-
      {{ not exclude_devices_enabled or (excluded_devices == none or excluded_devices | length == 0 or trigger.event.data.device_id not in excluded_devices) }}
  - condition: template
    value_template: |-
      {{ not include_devices_enabled or (include_devices != none and include_devices | length > 0 and trigger.event.data.device_id in include_devices) }}
  - alias: User pick
    condition: !input additional_conditions

actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - low
        sequence:
          - if:
              - condition: template
                value_template: "{{ low_notification }}"
            then:
              - action: persistent_notification.create
                data:
                  title: |
                    {{ trigger.event.data.device_name }} Battery Low
                  notification_id: "battery_notes_threshold {{ trigger.event.data.device_id }}-{{ trigger.event.data.source_entity_id }}"
                  message: >
                    The device has a battery level of {{
                    trigger.event.data.battery_level }}% {{ '\n' -}} You need {{
                    trigger.event.data.battery_quantity }}× {{
                    trigger.event.data.battery_type }}
          - alias: "Run user on low actions"
            choose: []
            default: !input "on_low_actions"
      - conditions:
          - condition: trigger
            id:
              - high
        sequence:
          - if:
              - condition: template
                value_template: "{{ low_notification }}"
            then:
              - action: persistent_notification.dismiss
                data:
                  notification_id: "battery_notes_threshold {{ trigger.event.data.device_id }}-{{ trigger.event.data.source_entity_id }}"
          - alias: "Run user on high actions"
            choose: []
            default: !input "on_high_actions"

mode: queued
