name: New Device
description: Submit a new device to the library so that others don't have to configure it themselves.
title: "[Device]: "
labels: ["new-device"]
body:
  - type: markdown
    attributes:
      value: |
        The battery library is a JSON document at [custom_components/battery_notes/data/library.json](https://github.com/andrew-codechimp/HA-Battery-Notes/blob/main/custom_components/battery_notes/data/library.json)
        To contribute, submit your device details via this form and the relevant code changes will be proposed on your behalf.
        Note: The manufacturer and model should be exactly what is displayed on the Device screen within Home Assistant.
        To see your devices, click here:

        [![Open your Home Assistant instance and show your devices.](https://my.home-assistant.io/badges/devices.svg)](https://my.home-assistant.io/redirect/devices/)

  - type: input
    id: manufacturer
    attributes:
      label: Manufacturer
      description: The manufacturer should be exactly what is displayed on the Devices screen within Home Assistant.
      placeholder: ex. eWeLink
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model
      description: The model should be exactly what is displayed on the Devices screen within Home Assistant.
      placeholder: ex. DS01
    validations:
      required: true

  - type: input
    id: battery-type
    attributes:
      label: Battery Type
      description: When specifying battery types please use the Most Common naming for general batteries and the IEC naming for battery cells according to [Wikipedia](https://en.wikipedia.org/wiki/List_of_battery_sizes).
      placeholder: ex. CR2032
    validations:
      required: true

  - type: input
    id: battery-quantity
    attributes:
      label: Battery Quantity
      description: The battery_quantity attribute is numeric (no letters or special characters).
      placeholder: ex. 1
    validations:
      required: true
