
set_battery_changed:
  name: Set battery changed
  description: "Set the battery last changed date."
  fields:
    device_id:
      name: Device
      description: Device that has had it's battery changed.
      required: true
      selector:
        device:
          filter:
            - integration: battery_notes
    datetime_changed:
      name: Date & time changed
      description: Date & time battery changed, defaults to now.
      required: false
      selector:
        datetime:
