
set_battery_replaced:
  name: Set battery replaced
  description: "Set the battery last replaced."
  fields:
    device_id:
      name: Device
      description: Device that has had it's battery replaced.
      required: true
      selector:
        device:
          filter:
            - integration: battery_notes
    datetime_replaced:
      name: Date
      description: Date replaced.
      required: false
      selector:
        datetime:
