#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    uv run hass --config "${PWD}/config" --script ensure_config
fi

# Start Home Assistant
uv run hass --config "${PWD}/config" --debug
