name: Tests

on:
  push:
    branches:
      - "main"
    paths:
      - '**.py' # Run if pushed commits include a change to a Python (.py) file.
      - 'library/library.json' # Library matching tests use the bundled library.
      - '.github/workflows/tests.yaml' # Run if pushed commits include a change to this workflow file.
      - 'pyproject.toml' # Run if project configuration file changes.
      - 'uv.lock' # Run if dependencies change.
  pull_request:
    branches:
      - "main"
    paths:
      - '**.py'
      - 'library/library.json'
      - '.github/workflows/tests.yaml'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest tests -v
